### ISSUE TITLE
如何配置新建模型的api问题

### ISSUE THREAD

**Issue by zhangsanfu** [Deali-Axy/DjangoStarter#1]
比如我新建一个应用 比如Books，之后，自动生成
```
__init__.py
apps.py
serializers.py
urls.py
viewsets.py
```
这四个文件了，能否直接也给这个新的应用生成一个api呢？
我研究了一下不太清楚在哪里添加这个路由，谢谢

**Comment by Deali-Axy** [comment]
你好，apps.demo是我之前测试代码生成器用的，已经移除了。

新建app自动生成的文件应该是类似下面这样的：

```python
__init__.py
apps.py
models.py
urls.py
views.py
```

之后参考文档，设计好`models.py`里的模型，运行代码生成命令：

```bash
python manage.py generate_code [app_label] [verbose_name]
```

代码生成器会生成你需要的所有代码，之后在`config/urls.py`文件中添加路由就行：

```python
urlpatterns = [
    path(f'core/', include('apps.core.urls')),
    # 需要根据你的App名称添加这一行路由
    path(app_label/', include('apps.app_label.urls')),
    # ...
]
```

**Comment by zhangsanfu** [comment]
@Deali-Axy \我就是按照您的方法添加了路由。比如我新建的app为blog，然后在config/urls.py添加了path('blog/', include('apps.blog.urls')),接下来访问http://127.0.0.1:8000/blog/的时候并没有出现api列表，麻烦再次请教一下，比如怎么才能显示出比如列表的api或者是详情的api，我尝试过http://127.0.0.1:8000/blog/article/这种地址，打开页面之后都是空白页面啥也没有，请教下是哪里配置不正确呢

**Comment by Deali-Axy** [comment]
你好，默认屏蔽RestFramework的api页面是本项目的功能呀，文档中有注明的

>集成RestFramework，默认屏蔽了链接主页，即对外隐藏API

你的意思应该是要查看Api文档，本项目集成了swagger文档，配置完成之后访问`http://127.0.0.1:8000/api-docs/swagger`即可

**Comment by zhangsanfu** [comment]
> 你好，默认屏蔽RestFramework的api页面是本项目的功能呀，文档中有注明的
> 
> > 集成RestFramework，默认屏蔽了链接主页，即对外隐藏API
> 
> 你的意思应该是要查看Api文档，本项目集成了swagger文档，配置完成之后访问`http://127.0.0.1:8000/api-docs/swagger`即可

谢谢，明白了

**Comment by Deali-Axy** [comment]
> > 你好，默认屏蔽RestFramework的api页面是本项目的功能呀，文档中有注明的
> > > 集成RestFramework，默认屏蔽了链接主页，即对外隐藏API
> > 
> > 
> > 你的意思应该是要查看Api文档，本项目集成了swagger文档，配置完成之后访问`http://127.0.0.1:8000/api-docs/swagger`即可
> 
> 谢谢，明白了

不客气，如果想恢复RestFramework默认的API页面，可以尝试以下操作之一

- 将`templates/rest_framework/base.html`文件删除
- 在`config/rest_framework.py`文件中，取消`'DEFAULT_RENDERER_CLASSES': ['rest_framework.renderers.JSONRenderer'],`这一行的注释
