### ISSUE TITLE
使用pip安装依赖全报错

### ISSUE THREAD

**Issue by 18621621452** [Deali-Axy/DjangoStarter#15]
python版本：python3.8.2，目前使用你V2版本。
pip install -r requirements.txt

ERROR: Could not find a version that satisfies the requirement asgiref==3.6.0 (from -r requirements.txt (line 1)) (from versions: none)
ERROR: No matching distribution found for asgiref==3.6.0 (from -r requirements.txt (line 1))

**Comment by Deali-Axy** [comment]
去除asgiref后面的版本号试试

将

```
asgiref==3.6.0
```

改成

```
asgiref
```

**Comment by 18621621452** [comment]
我测试过，应该和有些包在外网有关
