### ISSUE TITLE
想请教一下api的好处

### ISSUE THREAD

**Issue by zhangsanfu** [Deali-Axy/DjangoStarter#2]
楼主，您好，我最近研究了这个项目有段时间了，基本了解了这个项目的思路。我有个问题就是，比如我使用还是模板的方式调用数据，这个时候，我还是得使用api返回的数据，然后写入到模板中。
比如：
```
def home(request):
    response = requests.get('http://xxx.net/json/')
```
这个用法，我突然发现和我直接使用Book.objects.all()并无多大区别，我想问问这个api弄好之后，如果使用模板的话，有没有更容易的方式来使用呢？谢谢您

**Comment by Deali-Axy** [comment]
你好，“模板的方式”指的是用Django模板来渲染网页吗？本项目是为了前后端分离开发设计的，模板渲染网页属于前后端耦合开发，可以不需要使用api，直接在各个App的views.py文件中写视图函数就行。

我看你用了requests来请求，同个系统中这样写就绕了一个大圈了，没必要，直接Book.objects.all()就好了
