### ISSUE TITLE
联合主键修改数据会报错

### ISSUE THREAD

**Issue by zqxvip** [Deali-Axy/DjangoStarter#4]
生成的 model 里设置了联合主键 都是修改的时候还是会报错

**Comment by Deali-Axy** [comment]
具体报错信息麻烦提供一下

**Comment by zqxvip** [comment]
是在点击查询列表中的主键列，对这条数据进行编辑的时候报错
[报错.txt](https://github.com/Deali-Axy/DjangoStarter/files/7209029/default.txt)

**Comment by Deali-Axy** [comment]
方便提供一下models代码？用的什么数据库？代码生成器不会生成或者修改models的，请检查model定义是否有问题

**Comment by zqxvip** [comment]
数据库是 mysql8  model 是用 django 的inspectdb命令生成的
class AlFundFactorHis(models.Model):
    fund_code = models.CharField(primary_key=True, max_length=32)
    l1w = models.FloatField(blank=True, null=True)
    l1m = models.FloatField(blank=True, null=True)
    ytd = models.FloatField(blank=True, null=True)
    update_time = models.DateTimeField(blank=True, null=True)
    create_time = models.DateTimeField()
    enddate = models.CharField(max_length=8)
    volatility_l1m = models.FloatField(blank=True, null=True)
    volatility_l3m = models.FloatField(blank=True, null=True)
    volatility_ytd = models.FloatField(blank=True, null=True)
    compound_nav = models.FloatField()

    class Meta:
        managed = False
        db_table = 'al_fund_factor_his'
        unique_together = (('fund_code', 'enddate'),)

**Comment by Deali-Axy** [comment]
这个问题应该是你模型定义不当，参考：https://stackoverflow.com/questions/32172934/how-to-catch-the-multipleobjectsreturned-error-in-django
