### ISSUE TITLE
新架构跑不起来

### ISSUE THREAD

**Issue by 506688994** [Deali-Axy/DjangoStarter#6]
### **> 因为有几个名称是重复的，没有达到覆盖的效果**
![image](https://user-images.githubusercontent.com/45871200/192699108-38fe2c43-0576-4202-911f-6c9cd825f8fd.png)

### **> 运行会出现如下报错**
![image](https://user-images.githubusercontent.com/45871200/192699307-1d21d2d9-7d75-47d3-859c-4cd4e36bacbf.png)

**Comment by Deali-Axy** [comment]
抱歉，新架构还在开发中，这部分问题会在下次版本提交解决。

**Comment by Deali-Axy** [comment]
现在可以先使用这个版本 [3e1dc470698d6ae04095f9249c0c7d564947a559](https://github.com/Deali-Axy/DjangoStarter/commit/3e1dc470698d6ae04095f9249c0c7d564947a559)
