### ISSUE TITLE
No such file or directory: '/C:/ci_310/cffi_1642682485096/work'

### ISSUE THREAD

**Issue by Tkid3** [Deali-Axy/DjangoStarter#7]
操作系统：Centos7 & docker的也报错了

pip install -r requirements.txt 提示报错，好像是依赖包有windows的包。麻烦看看哦~
![image](https://user-images.githubusercontent.com/33016125/193178533-4a521be6-cfb8-4ae6-b6dc-06362adaaba2.png)

**Comment by Tkid3** [comment]
找到原因了。requirements.txt 里file:///URL 仅在你本地文件系统上可用 。
处理方法：pip list --format=freeze > requirements.txt

**Comment by Deali-Axy** [comment]
赞，感谢指出，我来改一改~
